<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <RootNamespace>KraftverkUptime.Web</RootNamespace>
    <AssemblyName>KraftverkUptime.Web</AssemblyName>
    <UserSecretsId>kraftverkuptime-web</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KraftverkUptime.Core\KraftverkUptime.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.4" />
    <PackageReference Include="MudBlazor" Version="8.4.0" />
    <PackageReference Include="Blazor-ApexCharts" Version="6.0.0" />
  </ItemGroup>

</Project>
