namespace KraftverkUptime.Infrastructure.Persistence;

/// <summary>
/// Whitelist over de 117 SCADA-tags som finnes i Lindlands master-CSV-eksport
/// (export-117-tags-avg-hour-20260503-063627_MASTER.csv).
///
/// Brukes av <see cref="LindlandSignalMapSeeder"/> til å pre-populere
/// <c>core.signal_map</c> ved oppstart slik at SCADA-importen kan starte uten
/// at brukeren må mappe hver tag manuelt. Hvis fremtidige eksporter har nye
/// tags, blir de upserted automatisk via SCADA-import-pipeline-en (med
/// <c>SignalRole.Other</c> hvis de ikke matches mot eksisterende mønster).
///
/// Katalogen er isolert i egen fil for at seederen skal være lett å lese.
/// Endring krever revurdering av topology-mapping i seederens MapTag.
/// </summary>
public static class Lindland117TagCatalog
{
    public static readonly string[] Tags =
    [
        // BARSTDVT — uregulert dam, kun 2 sensor-tags
        "LINDLAND_BARSTDVT_KONTROLL_TOT_VF_PV",
        "LINDLAND_BARSTDVT_NIVA_SENSOR_PRI_KOTE_PV",

        // EIAVT — regulert magasin (posisjon 2)
        "LINDLAND_EIAVT_KONTROLL_AGC_DB_SP",
        "LINDLAND_EIAVT_KONTROLL_KOM_AL",
        "LINDLAND_EIAVT_KONTROLL_MAG_FYLLGRD_PV",
        "LINDLAND_EIAVT_KONTROLL_MAG_NALELOP_PV",
        "LINDLAND_EIAVT_KONTROLL_MAG_NEDBKAP_PV",
        "LINDLAND_EIAVT_KONTROLL_MAG_OVLOP_PV",
        "LINDLAND_EIAVT_KONTROLL_MAG_VOLUM_PV",
        "LINDLAND_EIAVT_KONTROLL_REG_LUKE1_POS_SP_SP_LAST",
        "LINDLAND_EIAVT_KONTROLL_REG_LUKE1_POS_SP_TM_PV",
        "LINDLAND_EIAVT_KONTROLL_REG_LUKE1_VF_SP_SP_LAST",
        "LINDLAND_EIAVT_KONTROLL_REG_LUKE1_VF_SP_TM_PV",
        "LINDLAND_EIAVT_KONTROLL_TOT_VF_PV",
        "LINDLAND_EIAVT_LUKE1_POS_PV",
        "LINDLAND_EIAVT_LUKE1_VF_PV",
        "LINDLAND_EIAVT_NIVA_SENSOR_PRI_HRV_PV",
        "LINDLAND_EIAVT_NIVA_SENSOR_PRI_KOTE_PV",
        "LINDLAND_EIAVT_NIVA_VTA_PV",

        // G1 — generator 1
        "LINDLAND_G1_GEN_COSPHI_PV",
        "LINDLAND_G1_GEN_F_PV",
        "LINDLAND_G1_GEN_P_PV",
        "LINDLAND_G1_GEN_Q_PV",
        "LINDLAND_G1_GEN_RADLAGER_DE_TEMP_PV",
        "LINDLAND_G1_GEN_RADLAGER_NDE_TEMP_PV",
        "LINDLAND_G1_GEN_TIMETELLER_PV",
        "LINDLAND_G1_GEN_TURTALL_PV",
        "LINDLAND_G1_HYDRL_OLJE_TEMP_PV",
        "LINDLAND_G1_HYDRL_OLJE_TRYKK_PV",
        "LINDLAND_G1_KJOLEVANN_KALD_TEMP_PV",
        "LINDLAND_G1_KONTROLL_AGC_DB_SP",
        "LINDLAND_G1_KONTROLL_KOM_AL",
        "LINDLAND_G1_KONTROLL_REG_NIVA_SP_SP_LAST",
        "LINDLAND_G1_KONTROLL_REG_NIVA_SP_TM_PV",
        "LINDLAND_G1_KONTROLL_REG_P_SP_SP_LAST",
        "LINDLAND_G1_KONTROLL_REG_P_SP_TM_PV",
        "LINDLAND_G1_RORGATE_VANN_TRYKK_PV",
        "LINDLAND_G1_SMOLJE_OLJE_TEMP_PV",
        "LINDLAND_G1_TURB_FALLHOYDE_TOTAL_PV",
        "LINDLAND_G1_TURB_LEDEAPP_POS_PV",
        "LINDLAND_G1_TURB_VANN_TRYKK_PV",
        "LINDLAND_G1_TURB_VF_PV",
        "LINDLAND_G1_TURB_VIRKNGRD_PV",

        // G2 — generator 2
        "LINDLAND_G2_GEN_COSPHI_PV",
        "LINDLAND_G2_GEN_F_PV",
        "LINDLAND_G2_GEN_KALDLUFT_TEMP_PV",
        "LINDLAND_G2_GEN_P_PV",
        "LINDLAND_G2_GEN_Q_PV",
        "LINDLAND_G2_GEN_RADLAGER_DE_TEMP_PV",
        "LINDLAND_G2_GEN_RADLAGER_NDE_TEMP_PV",
        "LINDLAND_G2_GEN_TIMETELLER_PV",
        "LINDLAND_G2_GEN_TURTALL_PV",
        "LINDLAND_G2_KONTROLL_AGC_DB_SP",
        "LINDLAND_G2_KONTROLL_KOM_AL",
        "LINDLAND_G2_KONTROLL_REG_NIVA_SP_SP_LAST",
        "LINDLAND_G2_KONTROLL_REG_NIVA_SP_TM_PV",
        "LINDLAND_G2_KONTROLL_REG_P_SP_SP_LAST",
        "LINDLAND_G2_KONTROLL_REG_P_SP_TM_PV",
        "LINDLAND_G2_RORGATE_VANN_TRYKK_PV",
        "LINDLAND_G2_TURB_FALLHOYDE_TOTAL_PV",
        "LINDLAND_G2_TURB_LEDEAPP_POS_PV",
        "LINDLAND_G2_TURB_VANN_TRYKK_PV",
        "LINDLAND_G2_TURB_VF_PV",
        "LINDLAND_G2_TURB_VIRKNGRD_PV",

        // HEIGRAVT — øverste regulert magasin
        "LINDLAND_HEIGRAVT_KONTROLL_AGC_DB_SP",
        "LINDLAND_HEIGRAVT_KONTROLL_KOM_AL",
        "LINDLAND_HEIGRAVT_KONTROLL_MAG_FYLLGRD_PV",
        "LINDLAND_HEIGRAVT_KONTROLL_MAG_NEDBKAP_PV",
        "LINDLAND_HEIGRAVT_KONTROLL_MAG_OVLOP_PV",
        "LINDLAND_HEIGRAVT_KONTROLL_MAG_VOLUM_PV",
        "LINDLAND_HEIGRAVT_KONTROLL_REG_LUKE1_POS_SP_SP_LAST",
        "LINDLAND_HEIGRAVT_KONTROLL_REG_LUKE1_POS_SP_TM_PV",
        "LINDLAND_HEIGRAVT_KONTROLL_REG_LUKE1_VF_SP_SP_LAST",
        "LINDLAND_HEIGRAVT_KONTROLL_REG_LUKE1_VF_SP_TM_PV",
        "LINDLAND_HEIGRAVT_KONTROLL_TOT_VF_PV",
        "LINDLAND_HEIGRAVT_LUKE1_POS_PV",
        "LINDLAND_HEIGRAVT_LUKE1_VF_PV",
        "LINDLAND_HEIGRAVT_MET_NEDBOR_FORR_DOGN_PV",
        "LINDLAND_HEIGRAVT_MET_NEDBOR_FORR_TIME_PV",
        "LINDLAND_HEIGRAVT_MET_NEDBOR_INNEV_DOGN_PV",
        "LINDLAND_HEIGRAVT_MET_NEDBOR_INNEV_TIME_PV",
        "LINDLAND_HEIGRAVT_NIVA_SENSOR_PRI_HRV_PV",
        "LINDLAND_HEIGRAVT_NIVA_SENSOR_PRI_KOTE_PV",
        "LINDLAND_HEIGRAVT_NIVA_VTA_PV",

        // INNTAK — Rosslandshølen, terminal-dam
        "LINDLAND_INNTAK_KONTROLL_MAG_FYLLGRD_PV",
        "LINDLAND_INNTAK_KONTROLL_MAG_NEDBKAP_PV",
        "LINDLAND_INNTAK_KONTROLL_MAG_OVLOP_PV",
        "LINDLAND_INNTAK_KONTROLL_MAG_VOLUM_PV",
        "LINDLAND_INNTAK_KONTROLL_TOT_VF_PV",
        "LINDLAND_INNTAK_MAGASIN_FYLLGRAD_PV",
        "LINDLAND_INNTAK_MAGASIN_NED_KAP_PV",
        "LINDLAND_INNTAK_MAGASIN_VOLUM_PV",
        "LINDLAND_INNTAK_MINVF_CM_PV",
        "LINDLAND_INNTAK_MINVF_LITER_PV",
        "LINDLAND_INNTAK_MINVF_NIVA_OFFSET_SP_LAST",
        "LINDLAND_INNTAK_MINVF_NIVA_OFFSET_TM_PV",
        "LINDLAND_INNTAK_NIVA_NEDSTROM_KOTE_PV",
        "LINDLAND_INNTAK_NIVA_NEDSTROM_OFFSET_SP_LAST",
        "LINDLAND_INNTAK_NIVA_NEDSTROM_OFFSET_TM_PV",
        "LINDLAND_INNTAK_NIVA_OPPSTROM_KOTE_PV",
        "LINDLAND_INNTAK_NIVA_OPPSTROM_OFFSET_SP_LAST",
        "LINDLAND_INNTAK_NIVA_OPPSTROM_OFFSET_TM_PV",
        "LINDLAND_INNTAK_NIVA_OVERLOP_VF_PV",
        "LINDLAND_INNTAK_NIVA_SENSOR_PRI_HRV_PV",
        "LINDLAND_INNTAK_NIVA_VTA_PV",
        "LINDLAND_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_SP_LAST",
        "LINDLAND_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_TM_PV",
        "LINDLAND_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_SP_LAST",
        "LINDLAND_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_TM_PV",
        "LINDLAND_INNTAK_RISTRENSK_MAKS_PADRAG_G2_SP_SP_LAST",
        "LINDLAND_INNTAK_RISTRENSK_MAKS_PADRAG_G2_SP_TM_PV",
        "LINDLAND_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_SP_LAST",
        "LINDLAND_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_TM_PV",
        "LINDLAND_INNTAK_RIST_FALLTAP_PV",

        // KRST — sensor-stasjon på utløp etter turbinene
        "LINDLAND_KRST_KONTROLL_KOM_AL",
        "LINDLAND_KRST_NIVA_UTLOP_PV",

        // NETT — elektrisk avgangsside
        "LINDLAND_NETT_LINJE_FASE_L1_U_L1_L2_PV",
    ];
}
